// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtalrxeqjlriqbnnolfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0YWxyeGVxamxyaXFibm5vbGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzIyNjMsImV4cCI6MjA2NDcwODI2M30.4TIyMwydtmS50Pgrkkhw16JKIW1k6w17U6CsHIl__qs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
