
// This file is automatically generated. Do not edit it directly.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      package_requests: {
        Row: {
          id: string
          created_at: string
          email: string
          services: Json
          points: number
          marketing_consent: boolean
          status: string
        }
        Insert: {
          id?: string
          created_at?: string
          email: string
          services: Json
          points: number
          marketing_consent?: boolean
          status?: string
        }
        Update: {
          id?: string
          created_at?: string
          email?: string
          services?: Json
          points?: number
          marketing_consent?: boolean
          status?: string
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
